name: Reusable Workflow caller

on:
  push:
    branches:
      - main

jobs:
  call_workflow_in_remote_repository_after_renaming_secret:
    uses: jaap17/ArtifactsPassingToMultipleJobs/.github/workflows/clone_repo_using_gh_pat.yaml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
